#!/usr/bin/env groovy

node("ubuntu-vm-slave"){

	def environment = docker.build 'containerd'
	environment.inside {

		stage("Pulling latest containerd"){
			// get containerd
			sh "cd /go/src/github.com/containerd && \
				git clone \"https://github.com/containerd/containerd.git\""

		}
		stage("Running make binaries install test"){
			sh "cd /go/src/github.com/containerd && \
				make binaries install test integration root-test"
		}
	}
}
